
[functions.withdraw-near]
enabled = true
verify_jwt = true
import_map = "./functions/withdraw-near/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/withdraw-near/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/withdraw-near/*.html" ]

[functions.jomo-staking]
enabled = true
verify_jwt = true
import_map = "./functions/jomo-staking/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/jomo-staking/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/jomo-staking/*.html" ]

[functions.create-near-wallet]
enabled = true
verify_jwt = true
import_map = "./functions/create-near-wallet/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-near-wallet/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-near-wallet/*.html" ]
