name: Scheduled Prize Draw

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NEAR CLI
        run: npm install -g near-cli

      - name: Setup Credentials and Execute
        env:
          NEAR_CREDENTIALS: ${{ secrets.NEAR_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.near-credentials/mainnet
          
          echo "$NEAR_CREDENTIALS" > ~/.near-credentials/mainnet/crypto-jomo.near.json
          
          echo "Processing new deposits..."
          near call jomo-pool-v2.near process_draw "{}" --accountId crypto-jomo.near --networkId mainnet --gas 100000000000000
          
          echo "Drawing the winner..."
          near call jomo-pool-v2.near draw_winner "{}" --accountId crypto-jomo.near --networkId mainnet --gas 100000000000000